fix usage of twistd.daemonize() for Twisted 12.1.0 and above
twistd.daemonize() takes two parameters since Twisted 12.1.0, resulting
in the following traceback in bley:
Traceback (most recent call last):
  File "./bley", line 221, in
    bley_start()
  File "./bley", line 184, in bley_start
    twistd.daemonize()
TypeError: daemonize() takes exactly 2 arguments (0 given)

Check which version of Twisted we are running and act accordingly.

Closes #6